### ISSUE TITLE
Cookie Overload

### ISSUE THREAD

**Issue by jubjamie** [backstagetechnicalservices/website#1]
I really have no idea what's going on here. Source code obviously shows all the banners. Struggled to reproduce. Happy for you to mark as closed but thought i'd alert you.

![image](https://user-images.githubusercontent.com/25011496/33809293-aeffb95c-ddec-11e7-8a1e-8af2a9d77466.png)

**Comment by bnjns** [comment]
I've known it to produce a couple of notifications simultaneously, but never this many - can you elaborate on what you were doing to make this many appear?

**Comment by bnjns** [comment]
(Also, this is a bug with https://github.com/bnjns/laravel-notifications - can you submit the bug there instead?)
