### ISSUE TITLE
Single day meeting error

### ISSUE THREAD

**Issue by Daniel-Hanvey** [backstagetechnicalservices/website#23]
See the picture - If the meeting is on a single day, website doesn't like it.
![image](https://cloud.githubusercontent.com/assets/14125416/9682922/12b8366c-5303-11e5-8888-44ad34f6ea2b.png)

**Comment by bnjns** [comment]
This is a problem with Laravel - it doesn't support an "after or equal to" validation rule.

As a work-around I'll add the ability to hide that 2nd date entry for single day events.
