### ISSUE TITLE
Write documentation on how to use the website

### ISSUE THREAD

**Issue by bnjns** [backstagetechnicalservices/website#29]
Write documentation instructing users on how to use the various parts of the website. This should include both modal forms for each individual part and a knowledge base where users can look through all the documentation.

-----

Help documentation currently exists for:

* Creating users
* Committee election procedure
* Committee position descriptions

**Comment by bnjns** [comment]
@jubjamie are you willing to help with this over the summer / next year?

**Comment by jubjamie** [comment]
Yeah sure. To keep me organised can I suggest that you write a set of issues for bits that need doing (such as privacy policy) and assign them to me? I can start ticking bits off. Would also be good to have a virtual sit down with you at some point to go over more in depth web site stuff :)

**Comment by bnjns** [comment]
Yeah sure - the privacy policy and GDPR stuff will be completely separate. This is more for bits of the website that people may want/need guidance on how to use.

**Comment by tom98784** [comment]
I'm happy to write a bit of this too, as PM I end up doing a fair bit of website

**Comment by bnjns** [comment]
Cool - I shall leave you 2 to it :)

It'll be up to you as to how you want this to be stored. Some options are KB on the site, here on the GitHub repo as a wiki, etc.
