### ISSUE TITLE
[Feedback] Event Tab System

### ISSUE THREAD

**Issue by jubjamie** [backstagetechnicalservices/website#3]
Opinion. The tab system for the events on desktop creates a waste of space. Whereas the system does not show up on mobile where it might actually be more useful. Makes at a glance viewing of events difficult. What were the thoughts from the testing?

![image](https://user-images.githubusercontent.com/25011496/33809359-8da1e36a-dded-11e7-9215-0d50da2dff54.png)

**Comment by bnjns** [comment]
The events system was moved from it's old layout to a tabbed system to allow adding future functionality, such as kit lists, finance, etc - these simply wouldn't work with the old layout. I admit that some of the tabs aren't the best use of space on desktop, but in my opinion it's the most elegant solution and isn't that big of an issue - desktops are getting bigger and bigger and you simply can't make a site perfect for a range as large as 300px->2000px wide.
