### ISSUE TITLE
Logout button

### ISSUE THREAD

**Issue by enygma999** [backstagetechnicalservices/website#32]
I'd like a logout button for people (like me) who forget to use private browsing in the office and just rely on being paranoid maniacs who log out of everything. Even something as simple as a button that loads /logout would do :)

**Comment by bnjns** [comment]
I am very much against these, but I know it would probably be useful.

I'll investigate where I can put it.

**Comment by enygma999** [comment]
Bottom of the "Members area" list when logged in?

**Comment by bnjns** [comment]
Could do. It is where I used to have it.

**Comment by 36degrees** [comment]
Don't think it's worth a new issue (because I'm just being pedantic) but…

http://notaverb.com/logout

Likewise login – currently use a mix of 'login' / 'log in' on the log in screen.

:wink:
