### ISSUE TITLE
Rewrite privacy policy

### ISSUE THREAD

**Issue by bnjns** [backstagetechnicalservices/website#35]
Rewrite the privacy policy to be more specific as to what data is collected and how it is used. This needs to include a more detailed description of how cookies are used throughout the site.

**Comment by jubjamie** [comment]
I have made additions and amendments to the privacy policy including where data is used and shared. I feel that the current description of cookie usage is adequate for the website however if you feel this is not the case then I would reccommend you reopen and edit the privacy policy to include it.  For now I feel this is adequate for covering the website solely. I debated where I should include other Backstage "privacy policy things" for items like the mailing list but did not feel is was a suitable or obvious location for that content without clogging up the actual website policy. Closing.

Remember to return here to detail the change made as it's an uncommitted change on github!
