### ISSUE TITLE
Skill award list

### ISSUE THREAD

**Issue by enygma999** [backstagetechnicalservices/website#37]
Limit the list of skills you can select to award to the ones you are actually allowed to award, rather than produce an error message when they try to award a skill they can't?

**Comment by bnjns** [comment]
Do you mean on the skills index?

**Comment by enygma999** [comment]
On the training skills page, when you push "Award Skill" a box pops up with 3 drop downs: Skill, Member and Level. If you select a skill that you don't have the right to award, when you click "Award skill" at the bottom of the pop-up it gives an error message, as it should. I just feel it would be smoother to have the Skill drop-down list restricted to only those skills you have the right to award.

**Comment by enygma999** [comment]
![untitled](https://cloud.githubusercontent.com/assets/155104/9836296/df586390-5a0b-11e5-94eb-8a9db1256a45.png)
