### ISSUE TITLE
Ticks/Crosses on awarded/unawarded skills

### ISSUE THREAD

**Issue by ACascarino** [backstagetechnicalservices/website#38]
When viewing reviewed skill proposals, all entries have a green tick to the left. Might this make more sense to be a red cross if the skill was unawarded, and something yellow and intermediate-looking if the awarded skill was less than asked for but still awarded? (and possibly something super-green and sparkly if awarded level was more than asked for but that might be a bit cheesy)

**Comment by bnjns** [comment]
The tick/cross was to indicate whether the proposal had been processed (before I moved it to 2 lists) but I like this idea.

**Comment by bnjns** [comment]
This was fixed in 34b6e906de775e53d880b632fbefc4c8e7c19039
