### ISSUE TITLE
Can't add tags when adding new resources

### ISSUE THREAD

**Issue by tom98784** [backstagetechnicalservices/website#38]
When adding a resource to the website through the 'add resources' page form, the 'tags' field just shows a list of all possible tags and does not allow for addition/selection of tags.

**Comment by bnjns** [comment]
This is by design for various reasons, including avoiding duplicate tags. If you have suggestions for tags, I recommend letting the Secretary know :)

**Comment by tom98784** [comment]
To clarify, I was referring to what I believe to be a bug - I can't select tags from the selection available when adding a resource.

**Comment by tom98784** [comment]
I can select one tag or tags in a row, I can't pick out a selection of them though

**Comment by bnjns** [comment]
Again I can - use Control or Command to select multiple. Although I have fixed the select2 interface so this will be easier.
