### ISSUE TITLE
No use of cookies disclaimer 

### ISSUE THREAD

**Issue by alexrj92** [backstagetechnicalservices/website#39]
Godwin emailed this as well

**Comment by bnjns** [comment]
I mentioned this a while ago - not my job.

**Comment by alexrj92** [comment]
Surely there is a module we can use that has an accept like every other
website?

On Sunday, September 13, 2015, Ben Jones <notifications@github.com> wrote:

> I mentioned this a while ago - not my job.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/backstagetechnicalservices/website/issues/39#issuecomment-139872771>
> .
>


-- 
Kind Regards,

Alex Joseph



*Alex Joseph*

m:0 <0776563414>7765634614 | e:al <aj376@bath.ac.uk>exrj92@gmail.com | w:www
<http://www.bts-crew.com/>.photos. alexjoseph.co.uk

**Comment by bnjns** [comment]
Yes, but I'm not going to write the words. Someone else can do that because we also need a privacy policy.

**Comment by bnjns** [comment]
According to EU Law, we don't need a compliance message as we only use cookies for authentication, which are exempt.

We do need a privacy policy though - this can just be a webpage.
