### ISSUE TITLE
Equipment Breakage UI

### ISSUE THREAD

**Issue by jordanlkirk99** [backstagetechnicalservices/website#40]
Very poor use of space leading to unnecessary scrolling.

Item requires little space yet has a very wide column
Description has a lot of information but a narrow column

![image](https://user-images.githubusercontent.com/40248045/41374829-28e23d3a-6f4c-11e8-805b-a063e8cea0b2.png)

**Comment by bnjns** [comment]
This entire area needs a complete redesign. It was built that way to maintain as much backwards compatibility with the v2 as possible, but in hindsight that might not have been the best idea.

I suspect this may be worked on further alongside the asset register.
