### ISSUE TITLE
Navigation from My Profile to My Training via menu bar does not work.

### ISSUE THREAD

**Issue by ACascarino** [backstagetechnicalservices/website#41]
Pretty much as it says. Go to My Profile, then try to use the menu bar to get to My Training.

**Comment by ACascarino** [comment]
My Events has the same problem

**Comment by bnjns** [comment]
They do work if you're not already on the profile page. Potentially will change this in the future.

**Comment by ACascarino** [comment]
Yes, my point was that they don't work if you are on the profile page you mug.
