### ISSUE TITLE
Navigation Bar UI

### ISSUE THREAD

**Issue by jordanlkirk99** [backstagetechnicalservices/website#41]
Navigation bar is left aligned when the rest of the website (non-text) is centre aligned.
Looks odd and unbalanced. 

Also the vertical seperators between options are not equivalent. This seems to be an odd UI glitch as zoom level is altered so might not be a trivial fix

![image](https://user-images.githubusercontent.com/40248045/41375137-0f27f384-6f4d-11e8-90df-9a96b1859fad.png)

**Comment by bnjns** [comment]
I know what you mean, but that is just how navigation bars are typically made. The vertical separators is a limitation of computer displays being made from pixels and is not fixable.
