### ISSUE TITLE
BTS Awards Permission

### ISSUE THREAD

**Issue by jordanlkirk99** [backstagetechnicalservices/website#42]
I'm guessing non admins shouldn't have this drop down available?
![image](https://user-images.githubusercontent.com/40248045/41481767-1aedb350-70cb-11e8-9756-2fffbc81c8e3.png)

**Comment by bnjns** [comment]
Can you actually access those bits or is it just the dropdown you can see?

**Comment by jordanlkirk99** [comment]
I can open the edit window but when I apply I get a 404 error.
Delete pop ups the are you sure window, didn't try further

**Comment by bnjns** [comment]
Interesting.
