### ISSUE TITLE
External client SU email

### ISSUE THREAD

**Issue by hjbwynne** [backstagetechnicalservices/website#48]
The SU is automatically emailed when we add an external event to the events diary. The current recipient Alison Fleet should be updated to Paul Brooks.

**Comment by jordanlkirk99** [comment]
Does the accident report form recipient also want to be changed or just the external client notification (I'm assuming not)?

**Comment by bnjns** [comment]
All of them need changing - need to find an easier way of doing this in future.

**Comment by jordanlkirk99** [comment]
btw the salutation in the email will need updating aswell
