### ISSUE TITLE
Nickname request

### ISSUE THREAD

**Issue by Daniel-Hanvey** [backstagetechnicalservices/website#49]
Some members are better known by nicknames "Pixie, Mons, Faffington (!)"
Can I request EITHER an additional optional field for nicknames, or allow nicknames within the name field?

This would aid newer members who get told "Oh, ask Pixie", and be too nervous to ask who Pixie is...

**Comment by bnjns** [comment]
Yeah sure, Ben will get round to it because then he can call himself useful Ben and feel all special. 

Love Katie
