### ISSUE TITLE
List view for events

### ISSUE THREAD

**Issue by ACascarino** [backstagetechnicalservices/website#5]
During crew meetings it seemed advantageous to have all upcoming events in a list delimited by week. Would it be possible to add a tab to the events diary page which displays, for example, all events in the next x weeks?

**Comment by bnjns** [comment]
I can see its use but with the new events diary it's quite a bit easier to see this, as the individual times aren't displayed in the cell.

I'll keep it open but consider it 'low priority'.

**Comment by bnjns** [comment]
Shelved.
