### ISSUE TITLE
Cannot reject skills proposals

### ISSUE THREAD

**Issue by tom98784** [backstagetechnicalservices/website#54]
When a user proposes a skill level for themselves, the reviewer is given an 'awarded level' drop-down menu with the options of 'do not award' and the three levels, as well as a comment box. If 'do not award' is selected and the form is submitted, an error of 'please select a level that's available' is returned below the 'awarded level' menu, preventing completion of the skill proposal. This prevents skills reviewers from rejecting skills proposals that do not meet the required criteria for the skill.
![capture](https://user-images.githubusercontent.com/12998351/42137972-6a8bec02-7d6d-11e8-8676-270ab62ba319.PNG)

**Comment by bnjns** [comment]
This has been fixed by 7276b0c4219919cbff8653b35b52856e85c400b4.
