### ISSUE TITLE
Failed login: wording

### ISSUE THREAD

**Issue by Daniel-Hanvey** [backstagetechnicalservices/website#56]
When someone mistypes their password, it is not immediately obvious that the failed login is due to incorrect password. With more international students in the society, it may be worth re-wording the notification to be more clear and prevent needless emails requesting help.

**Comment by bnjns** [comment]
You don't do this so that anyone trying to hack into the site doesn't know what they got wrong.

**Comment by ACascarino** [comment]
Can we please change the wording of the message then? It definitely gives
the impression that the user's account doesn't exist.

Kind regards,
*Angel Cascarino*
*Production Manager 2015/16 - Backstage Technical Services*
