### ISSUE TITLE
Auto Close Award Nominatations

### ISSUE THREAD

**Issue by jordanlkirk99** [backstagetechnicalservices/website#60]
Nominations for awards should close as soon as voting starts.
2018 nominations are currently open yet the results are released.

**Comment by bnjns** [comment]
Nominations aren't open, and it's impossible for them to be once voting has opened because of how the system is designed.

**Comment by jordanlkirk99** [comment]
Sorry, by open I meant the nomination page was still visible and would allow submission without error.
(Gone now)
