### ISSUE TITLE
Dialog Box UI

### ISSUE THREAD

**Issue by jordanlkirk99** [backstagetechnicalservices/website#62]
Titles of dialog boxes and the crosses to dismiss them are oddly offset, surely they should be on the same line?
![image](https://user-images.githubusercontent.com/40248045/42506129-e089f350-8438-11e8-8453-3ae7f7b23b00.png)
![image](https://user-images.githubusercontent.com/40248045/42506133-e57df56e-8438-11e8-909c-a71929701bc1.png)

**Comment by bnjns** [comment]
Will probably be fixed during the update to Bootstrap 4. If not, re-open then.
