### ISSUE TITLE
Back button in resources section broken

### ISSUE THREAD

**Issue by jordanlkirk99** [backstagetechnicalservices/website#65]
The Back button found under documents in the resources section appears to just refresh the page.

How useful is this button? I'd imagine people just use the back button in their browser/OS.

**Comment by bnjns** [comment]
This was added because the old people like a back button :p It uses JS to redirect back, but this is always a bit dodgy depending on how you got to the page.

@enygma999 - you were an advocate for the back button - thoughts on whether it's needed?

**Comment by enygma999** [comment]
Was I? That does sound like me, but I can't remember why nor think of a reason right now. If it just triggers the browser's back function then probably no point in keeping it. Maybe I thought it would be a good idea to be able to go to the resources section that document was found in, no matter how you got to that document (ie if you were given a link or something), sort of link an up button on a folder tree or something :/ I'm sure if you take it out and I think of a reason to need one I'll complain about it then :D

**Comment by bnjns** [comment]
In which case, I agree with Jordan on removing it because I remember you complaining about it not quite knowing where to take you when it did work this way :p

And I'll ignore any future complaints about a lack of a back button :p

**Comment by enygma999** [comment]
Fair enough :)
