### ISSUE TITLE
Days start at 1am

### ISSUE THREAD

**Issue by ACascarino** [backstagetechnicalservices/website#66]
When setting an event time, it is regarded as falling on the previous day if the start time is before 1am.
As an example, if an event time of 00:01 on the 28th of May to 23:59 on the 28th of May is specified, the "event times" and events diary will show this as occuring on the 27th and carrying on through to the 28th; if it is set to start at 00:59, the same occurs, but if it is set to start at 01:00, the event will lie solely on the 28th. This error also tracks through to the finance database; if an event is created with the above error conditions, the finance db will regard it as starting on the 27th and finishing on the 28th.

**Comment by bnjns** [comment]
Can you give me an actual event this happens for so I can trace what's going wrong?

**Comment by bnjns** [comment]
This might be fixed in v4-dev - please have another look when v4.0 is released.
