### ISSUE TITLE
Updating training skills throws internal server error

### ISSUE THREAD

**Issue by kat-bts** [backstagetechnicalservices/website#70]
![image](https://user-images.githubusercontent.com/43783663/46350306-5a52f380-c64c-11e8-8d12-880ab2fa402c.png)
Hi,
When updating skill it does not save them and throws up error 500

Need this repairing asap for updates. I am logged in and this is repeatable

**Comment by bnjns** [comment]
Please provide some more information regarding how this error occurs.

What skills are you editing? What data are you changing (from what and to what?)? Is this for every skill? Only for certain skills (in which case, which skills?)?

**Comment by kat-bts** [comment]
Definitely for assistant chef when trying to fix the fact the description is blank, Other department skills aren't having this issue. from blank to writing. video advanced for example is fine. Appears to be a sporadic problem across skills

**Comment by bnjns** [comment]
Can you give me some examples of text that you can enter that breaks the skills that have this issue, and some text for the skills that don't break (you can stick them in a quote block here to make it easier to read)? Would make it much easier to dive in and see what's going on.

**Comment by bnjns** [comment]
Also, are you updating the description? The skill levels? Category?

**Comment by bnjns** [comment]
Final thing, you mentioned the issue being sporadic across skills. Can you give me a few more skills that do break, and a few more that don't? That will help significantly with tracking it down.

**Comment by jordanlkirk99** [comment]
It appears to be a problem with the uncategorised section.
Editing any skill within this section fails (name/descriptions/which levels are avalible)
Moving any skill into this section fails
Moving any skill out works fine and once moved the skill may be edited without issue

All other skills seem to function fine
