### ISSUE TITLE
Multiple User Add returns error on single user add page and doesn't appear to add the users.

### ISSUE THREAD

**Issue by jubjamie** [backstagetechnicalservices/website#71]
When I go to add in multiple users I get sent back to the singe user add page with an error saying the fields were not filled in. I'm not sure if it actually adds the users from the multiple user list. I have searched for the users with no results so i'm assuming not.

I have tried using a single entry and different single entries to see if it was an issue with the data/list of entries but that does not seem to be the case.

Perhaps the form is checking to see if the single add fields are completed and throwing the error without checking if single user add mode is actually being used?

**Comment by jordanlkirk99** [comment]
So adding users one at a time it throws no errors, but when you try to add multiple it fails?

**Comment by jubjamie** [comment]
If you use the single user mode it works fine, but the multiple user mode just throws you back to single user mode saying that you haven't filled in all the fields in the single user mode. I'm 99% sure it's not an error with the input data as I tried various bits as above.

**Comment by bnjns** [comment]
Did this happen last year at all? Or did you just use the single user mode last year?

**Comment by jubjamie** [comment]
I'm 95% certain I used multi mode last year. 

Fyi i have added all the members using single mode now so not urgent.

**Comment by bnjns** [comment]
Interesting. Is there anything that you've done differently this year compared to last year? Because of work I can't work on this during the week, but will try to find time at the weekend. Any more info (e.g., screenshots) would be very helpful with tracking down the problem.

**Comment by jubjamie** [comment]
I don't think so. I'll try and find some time to poke around to. If you can point me in the direction of the form validation I suspect that it's in there as it looks like it's not event submitting the form.

**Comment by jordanlkirk99** [comment]
Can't pretend to understand it but, looks like validation happens in the [user controller](https://github.com/backstagetechnicalservices/website/blob/b3cb54f99cfef22a74d184e2912179404dd035a1/app/Http/Controllers/Members/UsersController.php), starting at the storeBulk function.
