### ISSUE TITLE
Event timings broken

### ISSUE THREAD

**Issue by Daniel-Hanvey** [backstagetechnicalservices/website#76]
Adding a new time to a pre-existing event, finish time is viewed as being before start time
![image](https://cloud.githubusercontent.com/assets/14125416/13569559/98160390-e460-11e5-99b3-cff83ad00d3c.png)

**Comment by bnjns** [comment]
Whoops. Look at `App\Http\Controllers\EventsController::validateEventTime()` and the use of `App\Http\Requests\Request::createDateTimeEntry()`
