### ISSUE TITLE
Automatic time assignment for events

### ISSUE THREAD

**Issue by ACascarino** [backstagetechnicalservices/website#8]
Currently, if given date parameters whilst adding a new event, event timings are created that last from 00:00 to 23:59 on every date within the range given when creating the event. Would it be possible to add an automatic time assigner to this, so that for example 4 day shows with running times of 19:00 to 22:30 can be created in one command?

**Comment by bnjns** [comment]
That is a very sensible idea. Would you want this as an additional field to select or to be the default behaviour?

**Comment by ACascarino** [comment]
I think as default would probably be best, I'm reasonably sure I'm not
going to want to block out entire days for any actual events.

Kind regards,
*Angel Cascarino*
*Production Manager 2015/16 - Backstage Technical Services*

**Comment by ACascarino** [comment]
Ah. The current implementation, whilst significantly nicer, isn't quite what I had in mind! Rather, I envisioned being able to select what times you wanted your block to run from/until.

So for example I could create an event starting on 06/09/2015, finishing 10/09/2015, at times 14:00 - 16:30, and the event would be created with timings from 14:00 to 16:30 on the days specified. Does that make sense?

Apologies for not phrasing it correctly the first time.

**Comment by bnjns** [comment]
Ah, I got you. I've re-opened and I'll look at it when I do the deleting events.
