### ISSUE TITLE
AGM live stream

### ISSUE THREAD

**Issue by bnjns** [backstagetechnicalservices/website#83]
For the 2016 AGM we provided a live stream so that those unable to attend could still take part. However participating in votes was a pain because of the time delay and using the chat introduced ambiguity as to what vote the comments were for.

It would be brilliant to have a "meeting room" page which would have a video feed, a chat and could support creating votes. This would also remove the need for the Secretary to count votes manually - the system could be used by everyone.

**Comment by wrs20** [comment]
How easy is embedding a web irc client on a page on the website, with the irc server on the vps? There is probably a more elegant way of achieving the same thing (I am not a web developer). I like how if it is incorporated into the website there is no setup for users other than logging in.

**Comment by bnjns** [comment]
Good question - I don't know. It would be much better if we can stream it ourselves instead of relying on YouTube both for latency and access reasons. This is one of the arguments I had for paying for a VPS!

**Comment by freezemc** [comment]
I can setup a streaming service using rtmp on the VPS instead of using YouTube, would still have a delay of a few seconds (to allow for frame and connection speed drops) but it would doubtless be better than the delay on YT or Twitch.

**Comment by wrs20** [comment]
Iirc crtmpserver is fairly usable, we would have to ensure we were not going to go over the vps bandwidth limit for the month which is probably 1 or 2TB so this should be fine if the quality is sensible.
