### ISSUE TITLE
Resources order

### ISSUE THREAD

**Issue by enygma999** [backstagetechnicalservices/website#86]
Yay, the resources section has arrived! Ben is indeed awesome! :) But when I went and looked for crew meeting minutes they're in alphabetical order. Can we add a date order option at some point?

**Comment by bnjns** [comment]
Ideally yes and had they been added in order / when they were actually created I would have looked at doing it this way. As I added them yesterday/today trying to order by date will result in them being even less in order - as a result ordering by name is the most appropriate way at the moment.

**Comment by ACascarino** [comment]
Potentially might be worth looking at a way to tag resources within a
calendar, so you can list by "most recent event/meeting first/last"?


Kind regards,
*Angel Cascarino*
*Production Manager 2015/16 - Backstage Technical Services*

**Comment by ACascarino** [comment]
...and I realise I've literally just restated what Chris already said.
Oops. I'm dopey in the morning.

Kind regards,
*Angel Cascarino*
*Production Manager 2015/16 - Backstage Technical Services*

**Comment by bnjns** [comment]
So the reason I didn't put this up now is that you'd have to have a field that "represents" each resource and it's not a thing that's applicable to every type of resource. It's then potentially a disproportionate amount of code to implement and would unfairly skew results for those resources that don't have an associated date.

**Comment by bnjns** [comment]
I've re-looked into this for v4-dev, but I can't find a good way to do it.
