### ISSUE TITLE
Links to a specific event throws an error when not logged in

### ISSUE THREAD

**Issue by AHBabington** [backstagetechnicalservices/website#87]
May not work on other membership area pages as well. The website states
500 Fatal Error
Something Major Went Wrong

Unfortunately a fatal error occurred and further processing of this page had to be stopped. There isn't much you can do apart from try other pages to see if they work.

If you are an administrator you can refer to the error logs for more information.

This only happens when not logged in. Maybe make it so it re-directs to the login page or states you are not logged in.
![errorscreen](https://cloud.githubusercontent.com/assets/17915150/14924449/8ed613c0-0e3a-11e6-8cb0-0e12905db653.PNG)

**Comment by bnjns** [comment]
It should redirect or throw a 403 if not authorised - not something I have much control over as its handled by Laravel but I'll see if I've broken something somewhere.

**Comment by bnjns** [comment]
Fixed in v4-dev.
