### ISSUE TITLE
Dates on event pages

### ISSUE THREAD

**Issue by alexbabington** [backstagetechnicalservices/website#92]
![image](https://user-images.githubusercontent.com/33516326/32603685-86505d80-c542-11e7-8dbb-28b2d4bc8e2e.png)

Any chance of including the day of the week (i.e.: monday, tuesday, whatever) as well as the numerical date on the event pages. I find I'm bringing up the calender on my pc just to work out what date is what day of the week a lot of the time. It also means I have no idea if people are asking if I can do the event in crew meeting. I've attached an example from https://bts-crew.com/events/1719 .

Best Regards,

Alex

**Comment by bnjns** [comment]
Fixed in v4.0 because I 100% agree
